name = "refred"
main = "src/index.ts"
compatibility_date = "2023-06-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "refred.to/*", zone_name = "refred.to" }
]

[observability]
enabled = true

  [observability.logs]
  head_sampling_rate = 1

  [observability.traces]
  enabled = true
  head_sampling_rate = 0.01

[observability]
enabled = true

  [observability.logs]
  head_sampling_rate = 1

  [observability.traces]
  enabled = true
  head_sampling_rate = 0.01
