interface ResponseHeaders {
	[key: string]: string;
}

const SECURITY_HEADERS: ResponseHeaders = {
	'Content-Security-Policy': "default-src 'self'; img-src 'none';",
	'X-Robots-Tag': 'noindex, nofollow, noarchive, nosnippet',
	'X-Content-Type-Options': 'nosniff',
};

const NO_CACHE_HEADERS: ResponseHeaders = {
	'Cache-Control': 'no-store, no-cache, must-revalidate, proxy-revalidate',
	'Surrogate-Control': 'no-store',
	Pragma: 'no-cache',
	Expires: '0',
};

const MAX_SEGMENTS = 50;
const MAX_QUERY_LENGTH = 2000;

function badRequest(message: string): Response {
	return new Response(message, {
		status: 400,
		headers: SECURITY_HEADERS,
	});
}

function resolveBase(segments: string[], from: string | null): string[] | Response {
	if (from === null || from === 'current') return segments;
	if (from === 'root') return [];
	if (from === 'parent') return segments.slice(0, -1);

	if (/^-?\d+$/.test(from)) {
		const n = parseInt(from, 10);
		if (n >= 0) return segments.slice(0, Math.min(n, segments.length));
		return segments.slice(0, Math.max(0, segments.length + n));
	}

	const target = from.replace(/\/+$/, '').split('/');
	if (target.some((s) => s === '')) {
		return badRequest('Empty segments in "from" value');
	}

	for (let i = 0; i <= segments.length - target.length; i++) {
		if (target.every((t, j) => segments[i + j] === t)) {
			return segments.slice(0, i + target.length);
		}
	}

	return badRequest(`Segment path "${from}" not found in referer`);
}

export default {
	async fetch(
		request: Request,
		// @ts-expect-error `Env` is generated by `wrangler types` and may be empty if no bindings are configured
		_env: Env,
		_ctx: ExecutionContext,
	): Promise<Response> {
		const referer = request.headers.get('Referer');
		if (!referer) return badRequest('Referer header is missing or invalid');

		let refererUrl: URL;
		let requestUrl: URL;
		try {
			refererUrl = new URL(referer);
			requestUrl = new URL(request.url);
		} catch {
			return badRequest('Invalid referer URL');
		}

		if (refererUrl.protocol !== 'https:' && refererUrl.protocol !== 'http:') {
			return badRequest('Referer must be HTTP or HTTPS');
		}

		const segments = refererUrl.pathname.split('/').filter((s) => s !== '');
		if (segments.length > MAX_SEGMENTS) {
			return badRequest('Referer path too deep');
		}

		const fromParam = requestUrl.searchParams.get('from');
		if (fromParam !== null && fromParam.length > MAX_QUERY_LENGTH) {
			return badRequest('Query parameter too long');
		}

		const result = resolveBase(segments, fromParam);
		if (result instanceof Response) return result;

		const basePath = result.length > 0 ? `/${result.join('/')}` : '';
		const target = `https://${refererUrl.hostname}${basePath}${requestUrl.pathname}`;

		console.log(
			JSON.stringify({
				message: 'redirect',
				referer: refererUrl.hostname,
				path: requestUrl.pathname,
				target,
			}),
		);

		return new Response(null, {
			status: 302,
			headers: {
				...SECURITY_HEADERS,
				...NO_CACHE_HEADERS,
				Location: target,
			},
		});
	},
} satisfies ExportedHandler<Env>;
